### ISSUE TITLE
TS2345 Error

### ISSUE THREAD

**Issue by robertfg** [jerrynavi/diaries-app#1]
Hi, I'm getting this error in Auth.tsx:

TypeScript error in C:/Users/robertg/Git/play/diaries-app/src/features/auth/Auth.tsx(29,5):
Argument of type '{ validationSchema: Yup.ObjectSchema<object & { username: string; password: string; email: string; }>; }' is not assignable to parameter of type 'Partial<{ mode: "onBlur" | "onChange" | "onSubmit" | "all"; reValidateMode: "onBlur" | "onChange" | "onSubmit" | "all"; defaultValues: { id?: string; username?: string; email?: string; password?: string; diaryIds?: string[]; }; ... 4 more ...; criteriaMode: "all" | "firstError"; }>'.
  Object literal may only specify known properties, and 'validationSchema' does not exist in type 'Partial<{ mode: "onBlur" | "onChange" | "onSubmit" | "all"; reValidateMode: "onBlur" | "onChange" | "onSubmit" | "all"; defaultValues: { id?: string; username?: string; email?: string; password?: string; diaryIds?: string[]; }; ... 4 more ...; criteriaMode: "all" | "firstError"; }>'.  TS2345

```
```const { handleSubmit, register, errors } = useForm<User>({
```  validationSchema: schema,
```});
```

Any assistance would be appreciated.

**Comment by jerrynavi** [comment]
What version of React-Hook-Form are you using? `validationSchema` was removed in v6 and the tutorial was written with v5

**Comment by Mukarram-Ali26** [comment]
but it is still giving this error

TypeScript error in D:/Practical/my-diaries-app/src/features/auth/Auth.tsx(31,30):
Expected 0 arguments, but got 1.  TS2554

    29 |         if (res) {
    30 |           const { user, token } = res;
  > 31 |           dispatch(saveToken(token));
       |                              ^
    32 |           dispatch(setUser(user));
    33 |           dispatch(setAuthState(true));

**Comment by jerrynavi** [comment]
not sure why that is happening @Mukarram-Ali26. can you check and confirm that the saveToken fn accepts an argument?

**Comment by Mukarram-Ali26** [comment]
solved

**Comment by AbdulRahimFarooqui** [comment]
> What version of React-Hook-Form are you using? `validationSchema` was removed in v6 and the tutorial was written with v5

So, how can we fix this in v6? Any idea?

**Comment by Mukarram-Ali26** [comment]
I followed the documentation of router i am not sure now because i am not seeing the code you can check my diariesapp code in my repos i had solved that issues 5 months ago

**Comment by jerrynavi** [comment]
> > What version of React-Hook-Form are you using? `validationSchema` was removed in v6 and the tutorial was written with v5
> 
> So, how can we fix this in v6? Any idea?

@AbdulRahimFarooqui Please see this section on the v6 docs: https://react-hook-form.com/get-started#SchemaValidation

**Comment by AbdulRahimFarooqui** [comment]
Thanks @jerrynavi, just one more thing. I don't understand where is the createDiary function defined (the one used in src/services/mirage/routes/diary.ts line 21)?

**Comment by jerrynavi** [comment]
@AbdulRahimFarooqui the function is automatically generated by Mirage when you setup a relationship between models. See [this](https://github.com/jerrynavi/diaries-app/blob/31723ffff16889cd0b1aaf5b444c83ba03b6ec5a/src/services/mirage/server.ts#L27) and [this](https://miragejs.com/docs/main-concepts/relationships/#hasmany)
