### ISSUE TITLE
TS2571

### ISSUE THREAD

**Issue by Hasham-dev** [jerrynavi/diaries-app#2]
Just having these 2 issues any idea how to get resolve?
![image](https://user-images.githubusercontent.com/64362929/95263040-a4c46780-0846-11eb-86a8-0d6c7e8a611e.png)

**Comment by Hasham-dev** [comment]
Getting error in diary.tsx
if (result.value) { //error : object is of type "unkuown"
const { value } = result; //"undefined"
const {
diary,
user: _user,
} = await http.post<Partial<Diary>, { diary: Diary; user: User }>('/diaries/', {
title: value[0],
type: value[1],
userId: user?.id,
});

**Comment by jerrynavi** [comment]
@Hasham-dev I just pushed a fix. Let me know if that works for you.

**Comment by Hasham-dev** [comment]
Thanks, buddy I resolve it too

by just passing type on declared variable Result

Thanks for the brilliant Code :)
